default_context:
  project_name: 'FastAPI Template'
  project_slug: 'fastapi-template'
  domain_main: 'fastapi-app.com'
  domain_staging: 'staging.fastapi-app.com'
  docker_swarm_stack_name_main: 'fastapi-template-app'
  docker_swarm_stack_name_staging: 'staging-fastapi-app'
  secret_key: '425799d6a3d14bac9c3f30704b7d448ac745a0b993f7f491f6ea5f4637a2249d'
  first_superuser: 'admin@fastapi-app.com'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-app.com", "https://staging.fastapi-app.com", "https://fastapi-app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '1025'
  smtp_host: 'fastapi-mailhog'
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-app.com'
  postgres_password: '123456'
  pgadmin_default_user: 'admin@fastapi-app.com'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'fastapi-app.com'
  traefik_constraint_tag_staging: 'staging.fastapi-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: 'https://6916ff6fb999497bad9c61bc8d01db06@o1052875.ingest.sentry.io/6036787'
  docker_image_prefix: ''
  docker_image_backend: 'template-backend'
  docker_image_celeryworker: 'template-worker'
  docker_image_frontend: 'template-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
